package com.lyc.dao;

import com.lyc.dataobject.StockLogDo;

public interface StockLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Jul 30 14:57:01 CST 2019
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Jul 30 14:57:01 CST 2019
     */
    int insert(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Jul 30 14:57:01 CST 2019
     */
    int insertSelective(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Jul 30 14:57:01 CST 2019
     */
    StockLogDo selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Jul 30 14:57:01 CST 2019
     */
    int updateByPrimaryKeySelective(StockLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Jul 30 14:57:01 CST 2019
     */
    int updateByPrimaryKey(StockLogDo record);
}